#Analysis
import pandas as pd
#Customer Behaviour Analysis
def customer_behaviour(df):
    print("\n======Customer Behaviour Analysis======")
    print(f"Total Unique Customers:-{df['CustomerID'].nunique()}")

    print("Orders Per Customers:-")
    orders_per_customer = df.groupby('CustomerID')['InvoiceNo'].nunique().reset_index(name='Total_Orders')
    print(orders_per_customer)

    customer_revenue = df.groupby('CustomerID')['UnitPrice'].sum().reset_index(name='Total_Revenue')
    print ("\n",customer_revenue)

    avg_revenue = customer_revenue['Total_Revenue'].mean()
    print(f"Average Revenue per Customer: \n{avg_revenue:.2f}")

    repeat_customers = orders_per_customer[orders_per_customer['Total_Orders'] > 1]
    print(f"\n Repeat Customers:\n {repeat_customers}")

    repeat_rate = (len(repeat_customers) / len(orders_per_customer)) * 100
    print(f"\nRepeat Customer Rate: {repeat_rate:.2f}%")

def product_analysis(df):
    #Product category analysis.
    print("\n======Product Analysis======") 
    print(f"\nTotal Number of Unique Products:-{df['StockCode'].nunique()}")

    print(f"\nBest Selling Products:-\n{df.groupby(['StockCode','Description'])['Quantity'].sum().sort_values(ascending=False).reset_index(name='Quantity Sold').head(10)}")
    print(f"\nMost Frequently Purchased Products:-\n{df.groupby(['StockCode','Description'])['InvoiceNo'].nunique().sort_values(ascending=False).reset_index(name='Number of Orders').head(10)}")

    df['Revenue'] = df['Quantity'] * df['UnitPrice']
    print(f"\nTop Revenue-Generating Products:-\n{df.groupby('Description')['Revenue'].sum().sort_values(ascending=False).reset_index(name='Revenue per Product').head(10)}")

#Monthly sales trend.  
def monthly_analysis(df):
    print("\n======Monthly Sales Trend======")
    df['InvoiceDate'] = pd.to_datetime(df['InvoiceDate'])
    df['YearMonth'] = df['InvoiceDate'].dt.to_period('M')

    monthly_summary = (
    df.groupby('YearMonth')
      .agg(
          Monthly_Revenue=('Revenue', 'sum'),
          Total_Orders=('InvoiceNo', 'nunique'),
          Total_Quantity_Sold=('Quantity', 'sum')
      )
      .reset_index()
    )

    print(monthly_summary)

    # Customer Lifetime Value.  
def clv(df):
    print("\n======Customer Lifetime Value======")

    print("\nCLV for Each Customer")
    customer_clv = (
    df.groupby('CustomerID')['Revenue']
      .sum()
      .reset_index(name='CLV')
    )
    print(customer_clv.head())

    print(f"\nAverage CLV: {customer_clv['CLV'].mean():.2f}")

    print(f"\nTop 10 Customers by CLV:-\n{customer_clv.sort_values(by='CLV', ascending=False).head(10)}")

    print("\nCLV distribution")
    customer_clv['CLV_Category'] = pd.qcut(
    customer_clv['CLV'],
    q=3,
    labels=['Low', 'Medium', 'High']
    )
    print(customer_clv['CLV_Category'].value_counts())

# Top customer analysis.  
def top_customers(df):
    print("\n====== Top Customer Analysis.======")
    print(f"\nTop 10 customers by total spending:-\n{df.groupby('CustomerID')['UnitPrice'].sum().sort_values(ascending=False).reset_index(name='Amount').head(10)}")
    print(f"\nTop 10 customers by number of order:-\n{df.groupby('CustomerID')['InvoiceNo'].nunique().sort_values(ascending=False).reset_index(name='Orders').head(10)}")
    print(f"\nTop 10 customers by quantity purchased:-\n{df.groupby('CustomerID')['Quantity'].sum().sort_values(ascending=False).reset_index(name='Quantity').head(10)}")

# Revenue Analysis
def revenue_analysis(df):
    print("\n====== Revenue Analysis ======")
    total_revenue = df['Revenue'].sum()
    print(f"\nTotal Revenue: {total_revenue:.2f}")

    order_revenue = df.groupby('InvoiceNo')['Revenue'].sum()
    aov = order_revenue.mean()
    print(f"\nAverage Order Value: {aov:.2f}")

    print("\nRevenue by Country:-")
    revenue_country = (
    df.groupby('Country')['Revenue']
      .sum()
      .sort_values(ascending=False)
      .reset_index()
    )
    print(revenue_country.head(10))

#Product Profitability
def product_prof(df):
    product_revenue = (
    df.groupby(['StockCode', 'Description'])['Revenue']
      .sum()
      .sort_values(ascending=False)
      .reset_index(name='Revenue')
    )

    print("\nRevenue Generated by Each Product:-")
    print(product_revenue)

    print("\nHighest Revenue-Generating Products:-\n",product_revenue.head(10))

    print("\nLowest Revenue-Generating Products:-\n",product_revenue.tail(10))
